### ISSUE TITLE
stuff to do, to finish out KG2.7.4 build

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#183]
- [x] host in Neo4j
- [x] DNS
- [x] edit/update `kg2-versions.md`
- [x] merge `issue165` branch into `master` branch
- [x] check JSON reports (diff against previous reports, etc.)
- [x] KGX export of KG2.7.4pre (see #154)

**Comment by saramsey** [comment]
parent issue for the build is #166

**Comment by saramsey** [comment]
FWIW, I have also tagged the [master branch of RTX-KG2](https://github.com/RTXteam/RTX-KG2/tree/master) as `Dec21Demo`.

**Comment by saramsey** [comment]
But I note that RTX-KG2 is not listed as a KP on the SRI's deployment Google Sheet, so maybe it is not necessary to tag. I have tagged just in case there is a question of which code was used to build the KG2 that is being used for the demo.

**Comment by acevedol** [comment]
There were a lot of changes to the source labels and a new predicate curie `has real world evidence of association with`  due to changes in the biolink model, but edges and nodes increased and the changes look reasonable. The full diff is in the attached file `changes-in-2.7.4.log`

[changes-in-2.7.4.log](https://github.com/RTXteam/RTX-KG2/files/7688627/changes-in-2.7.4.log)

**Comment by saramsey** [comment]
Thank you @acevedol. The diffs look pretty reasonable to me, at least at a cursory inspection. Do you see any items of concern in the diff?

**Comment by acevedol** [comment]
No, I didn't have any concerns in the diff. The changes were all as expected due to the updated biolink model.
