### ISSUE TITLE
invalid predicate "rename:located_in" showing up

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#201]
This issue was reported by @maximusunc via [RTX Issue 1828](https://github.com/RTXteam/RTX/issues/1828) (thank you @maximusunc).

Apparently, in `predicate-remap.yaml`, there are three UBERON relations that are incorrectly mapped to `rename:located_in`:
https://github.com/RTXteam/RTX-KG2/blob/85bf397963c48a11cbb151c686fb7ab3401836f0/predicate-remap.yaml#L4540-L4551

they should be mapped to `biolink:located_in`, I think.

**Comment by saramsey** [comment]
Hi @acevedol we should also scan the `predicate-remap.yaml` file to see if any similar bugs are lurking, i.e., any other cases where the predicate starts with `rename:` (but with a different predicate label instead of `located_in`) instead of the correct predicate CURIE prefix, `biolink:`.

**Comment by acevedol** [comment]
I corrected the three invalid predicates on the `issue-199` branch. There do not appear to be any additional invalid predicates.

**Comment by acevedol** [comment]
@saramsey What is the protocol for a high priority bug like this? Should I rebuild ASAP?

**Comment by saramsey** [comment]
Can we close this out?  Is it fixed in the production RTX-KG2 service?

**Comment by acevedol** [comment]
@saramsey Yes, thank you for bringing this up. This was fixed in 2.7.6, I believe. I checked against neo4j and it shows no results for the relationship "rename:located_in" but several results for "biolink:located_in"
![Screen Shot 2022-10-06 at 2 54 04 PM](https://user-images.githubusercontent.com/59181061/194425647-0d6bdbd2-a252-402b-a997-9fcb1f89dd25.png)
