### ISSUE TITLE
Update setup scripts, organize new repo issues

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX-KG2#47]
This is a reminder for me to update anything that might be different now that KG2 has it's own repo

**Comment by kvarforl** [comment]
Questions:

- do we still want to create a symlink called `kg2-code`, or just change `master-config.shinc` to set `CODE_DIR` to `RTX-KG2`?
- Does travis ci need any other setting up than changing the path in this line? https://github.com/RTXteam/RTX-KG2/blob/fbb3cf4559923252e13a2a6e5756e5c6019277fe/setup-kg2-build.sh#L20

**Comment by ericawood** [comment]
> do we still want to create a symlink called `kg2-code`, or just change `master-config.shinc` to set `CODE_DIR` to `RTX-KG2`? My vote is to leave it sym linked to make future reorganizations less painful :)

I think we should still create a symlink because, so long as someone creates the symlink, users can have the non-symlinked code wherever they want. (But I agree, my first inclination is make it easy).

> Does travis ci need any other setting up than changing the path in this line? 
Yes, I'll work on that :)

**Comment by kvarforl** [comment]
Instance wise, I've updated kg2lindsey to use this repo. I'll update both kg2endpoints later this afternoon.

**Comment by ericawood** [comment]
Forgot to link it in the commit message, but commit edbf7c4 also falls under this issue.

**Comment by saramsey** [comment]
Good discussion here!  I will just chime in with a historical perspective. The reason for the sym-link was originally because the KG2 code-base was embedded several levels deep in the RTX repo (RTX/code/kg2), and so when the code was checked out locally on the EC2 instance in /home/ubuntu, the sym link made it easy to navigate to the code directory by doing
```
cd ~/kg2-code
```
So mostly, the sym link was for me to have to avoid typing
```
cd ~/RTX/code/kg2
```
so many times in the course of a day.
Of course, now that the code will be in `/home/ubuntu/RTX-KG2`, we no longer have that issue. I leave it up to you to decide!  :-)

**Comment by kvarforl** [comment]
I think that this is done! Marking to verify in the next build that nothing is horrifyingly broken :)

**Comment by ericawood** [comment]
This worked in the KG2.6.5 issue!
