### ISSUE TITLE
Gene/disease conflations in KG2C-6-3

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX-KG2#49]
I have noticed a number of KG2C-6-3 disease/gene conflations:
`match (n:`biolink:Disease`{id:"MONDO:0042979"}) return n` Gene CACNA1S conflated with the disease `Hypokalemic periodic paralysis`.

`match (n:`biolink:Disease`{id:"MONDO:0011309"}) return n` Gene TSHR conflated with disease `familial gestational hyperthyroidism`.

`match (n:`biolink:Disease`{id:"MONDO:0012276"}) return n` Gene KCNMA1 conflated with disease `eneralized epilepsy - paroxysmal dyskinesia`

Some/all of these look to be due to mutations in the gene causing the disease.

**Comment by kvarforl** [comment]
Okay I think we've made the problem different, but not necessarily better?
on kg2.6.4
```
MATCH (d:`biolink:Disease`)
MATCH (g:`biolink:Gene`)
WHERE d.name = g.name
RETURN d.id as disease,g.id as gene, d.name as name;
```
returns 3616 records (which is more than before). Here are some examples, chosen randomly to try to get a spread of the different provided by combos:

disease | gene | name
-- | -- | --
"UMLS:C1838854" | "HGNC:7497" | "MT-TS1"
"UMLS:C3809434" | "OMIM:609799" | "NEK8"
"UMLS:C3501265" | "OMIM:600970" | "MYO6"
"UMLS:C3715165" | "OMIM:600958" | "MYBPC3"
"UMLS:C3809346" | "OMIM:600958" | "MYBPC3"
"UMLS:C3810194" | "OMIM:609369" | "ATL3"
"UMLS:C3805411" | "OMIM:193060" | "VIM"
"UMLS:C1859252" | "OMIM:614123" | "TMCO1"
"UMLS:C1856603" | "ENSEMBL:ENSG00000001084" | "GCLC"
"UMLS:C1861786" | "ENSEMBL:ENSG00000001631" | "KRIT1"
"UMLS:C1861785" | "ENSEMBL:ENSG00000001631" | "KRIT1"
"UMLS:C1366911" | "ENSEMBL:ENSG00000001631" | "KRIT1"
"UMLS:C3280729" | "ENSEMBL:ENSG00000003137" | "CYP26B1"





Here is the provided by breakdown:
```
MATCH (d:`biolink:Disease`)
MATCH (g:`biolink:Gene`)
WHERE d.name = g.name
RETURN distinct(d.provided_by+" \\ "+ g.provided_by), count(*) order by count(*) DESC;
```

(d.provided_by+" \\ "+ g.provided_by) | count(*)
-- | --
"identifiers_org_registry:umls \ identifiers_org_registry:ensembl" | 2015
"identifiers_org_registry:umls \ umls_source:OMIM" | 1565
"OBO:mondo.owl \ ORPHANET:" | 9
"OBO:doid.owl \ ORPHANET:" | 9
"EFO:efo.owl \ ORPHANET:" | 8
"identifiers_org_registry:umls \ umls_source:HGNC" | 7
"umls_source:MSH \ ORPHANET:" | 3

**Comment by ericawood** [comment]
I think the problem might be with UMLS rather than with the data sources:

```
MATCH (d:`biolink:Disease`)
MATCH (g:`biolink:Gene`)
WHERE d.name = g.name
AND NOT (d)-[:`biolink:close_match`]-(g)
RETURN distinct(d.provided_by+" \\ "+ g.provided_by), count(*) order by count(*) DESC;
```


(d.provided_by+" \\ "+ g.provided_by) | count(*)
-- | --
"identifiers_org_registry:umls \ identifiers_org_registry:ensembl" | 2015
"OBO:mondo.owl \ ORPHANET:" | 9
"OBO:doid.owl \ ORPHANET:" | 9
"EFO:efo.owl \ ORPHANET:" | 8
"identifiers_org_registry:umls \ umls_source:HGNC" | 7
"umls_source:MSH \ ORPHANET:" | 3

You'll noticed all of the UMLS-OMIM equivalencies are wrong. This likely means that the UMLS CUI nodes are receiving the wrong category, likely from a different source.

**Comment by ericawood** [comment]
> You'll noticed all of the UMLS-OMIM equivalencies are gone. This likely means that the UMLS CUI nodes are receiving the wrong category, likely from a different source.

Ok, that is not the case. (For example, C3280729 is a disease not a gene, see https://www.ncbi.nlm.nih.gov/medgen/C3280729) I think the CUI nodes are getting the right category and (perhaps) we should ignore `has_cui` relationships from OMIM.

See: `match (n:`biolink:Disease` {id: 'UMLS:C3280729'})-[e {relation: 'oboFormat:xref'}]-(m) return n, e, m` as a reference. Both the genes and phenotypes from OMIM contribute to their respective CUI nodes. This is problematic because they have different names. Per 

https://github.com/RTXteam/RTX-KG2/blob/e6275ee3413b19edda1ee42cf7d7bb14d3beaa22/kg2_util.py#L538-L546

and

https://github.com/RTXteam/RTX-KG2/blob/e6275ee3413b19edda1ee42cf7d7bb14d3beaa22/kg2_util.py#L496-L505

the category and name for a node have different criteria for which one is picked in a merge. This is likely leading to an odd merge, but I haven't confirmed that.

**Comment by ericawood** [comment]
This is substantially better in KG2.6.5. I added an extra column in the below table (to the query) to note if this synonymization was already occurring. There were only 29 results to the query below:

```
MATCH (d:`biolink:Disease`)
MATCH (g:`biolink:Gene`)
WHERE d.name = g.name
RETURN d.id as disease,g.id as gene, d.name as name;
```

disease | gene | name | already occurring?
-- | -- | -- | --
"MESH:C537910" | "ORPHANET:118982" | "Bardet-Biedl syndrome 2" | yes
"MESH:C537912" | "ORPHANET:118985" | "Bardet-Biedl syndrome 4" | yes
"MESH:C537909" | "ORPHANET:118975" | "Bardet-Biedl syndrome 1" | yes
"ORPHANET:2473" | "ORPHANET:123245" | "McKusick-Kaufman syndrome" | yes
"EFO:0009023" | "ORPHANET:137646" | "Bardet-Biedl syndrome 12" | yes
"EFO:0009024" | "ORPHANET:118985" | "Bardet-Biedl syndrome 4" | yes
"EFO:0009021" | "ORPHANET:118975" | "Bardet-Biedl syndrome 1" | yes
"EFO:0009022" | "ORPHANET:118978" | "Bardet-Biedl syndrome 10" | yes
"EFO:0009027" | "ORPHANET:118994" | "Bardet-Biedl syndrome 9" | yes
"EFO:0009025" | "ORPHANET:118987" | "Bardet-Biedl syndrome 5" | yes
"EFO:0009026" | "ORPHANET:118990" | "Bardet-Biedl syndrome 7" | yes
"MONDO:0014440" | "ORPHANET:137646" | "Bardet-Biedl syndrome 12" | yes
"MONDO:0014435" | "ORPHANET:118990" | "Bardet-Biedl syndrome 7" | yes
"MONDO:0014434" | "ORPHANET:118987" | "Bardet-Biedl syndrome 5" | yes
"MONDO:0014433" | "ORPHANET:118985" | "Bardet-Biedl syndrome 4" | yes
"MONDO:0014432" | "ORPHANET:118982" | "Bardet-Biedl syndrome 2" | yes
"MONDO:0014438" | "ORPHANET:118978" | "Bardet-Biedl syndrome 10" | yes
"MONDO:0014437" | "ORPHANET:118994" | "Bardet-Biedl syndrome 9" | yes
"MONDO:0009367" | "ORPHANET:123245" | "McKusick-Kaufman syndrome" | yes
"MONDO:0008854" | "ORPHANET:118975" | "Bardet-Biedl syndrome 1" | yes
"DOID:0110124" | "ORPHANET:118982" | "Bardet-Biedl syndrome 2" | yes
"DOID:0110123" | "ORPHANET:118975" | "Bardet-Biedl syndrome 1" | yes
"DOID:0110129" | "ORPHANET:118990" | "Bardet-Biedl syndrome 7" | yes
"DOID:0110126" | "ORPHANET:118985" | "Bardet-Biedl syndrome 4" | yes
"DOID:0110127" | "ORPHANET:118987" | "Bardet-Biedl syndrome 5" | yes
"DOID:0110131" | "ORPHANET:118994" | "Bardet-Biedl syndrome 9" | yes
"DOID:0110132" | "ORPHANET:118978" | "Bardet-Biedl syndrome 10" | yes
"DOID:0110134" | "ORPHANET:137646" | "Bardet-Biedl syndrome 12" | yes
"DOID:0111255" | "ORPHANET:123245" | "McKusick-Kaufman syndrome" | yes

You will see that all of these gene/disease conflations present in KG2.6.5 were already present in KG2.5.2. Thus, it seems unnecessary to not roll out KG2.6.5 based on these 29 cases. I'm going to close out this issue for now.
